package com.aserbao.aserbaosandroid.functions.database.greenDao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.taxidata.bean.HotSpotHistorySearch;

import com.aserbao.aserbaosandroid.functions.database.greenDao.db.HotSpotHistorySearchDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hotSpotHistorySearchDaoConfig;

    private final HotSpotHistorySearchDao hotSpotHistorySearchDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hotSpotHistorySearchDaoConfig = daoConfigMap.get(HotSpotHistorySearchDao.class).clone();
        hotSpotHistorySearchDaoConfig.initIdentityScope(type);

        hotSpotHistorySearchDao = new HotSpotHistorySearchDao(hotSpotHistorySearchDaoConfig, this);

        registerDao(HotSpotHistorySearch.class, hotSpotHistorySearchDao);
    }
    
    public void clear() {
        hotSpotHistorySearchDaoConfig.clearIdentityScope();
    }

    public HotSpotHistorySearchDao getHotSpotHistorySearchDao() {
        return hotSpotHistorySearchDao;
    }

}
