package com.aserbao.aserbaosandroid.functions.database.greenDao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.taxidata.bean.HotSpotHistorySearch;
import com.example.taxidata.bean.HotSpotOrigin;
import com.example.taxidata.ui.passengerpath.enity.EndInfo;
import com.example.taxidata.ui.passengerpath.enity.OriginEndInfo;
import com.example.taxidata.ui.passengerpath.enity.OriginInfo;

import com.aserbao.aserbaosandroid.functions.database.greenDao.db.HotSpotHistorySearchDao;
import com.aserbao.aserbaosandroid.functions.database.greenDao.db.HotSpotOriginDao;
import com.aserbao.aserbaosandroid.functions.database.greenDao.db.EndInfoDao;
import com.aserbao.aserbaosandroid.functions.database.greenDao.db.OriginEndInfoDao;
import com.aserbao.aserbaosandroid.functions.database.greenDao.db.OriginInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hotSpotHistorySearchDaoConfig;
    private final DaoConfig hotSpotOriginDaoConfig;
    private final DaoConfig endInfoDaoConfig;
    private final DaoConfig originEndInfoDaoConfig;
    private final DaoConfig originInfoDaoConfig;

    private final HotSpotHistorySearchDao hotSpotHistorySearchDao;
    private final HotSpotOriginDao hotSpotOriginDao;
    private final EndInfoDao endInfoDao;
    private final OriginEndInfoDao originEndInfoDao;
    private final OriginInfoDao originInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hotSpotHistorySearchDaoConfig = daoConfigMap.get(HotSpotHistorySearchDao.class).clone();
        hotSpotHistorySearchDaoConfig.initIdentityScope(type);

        hotSpotOriginDaoConfig = daoConfigMap.get(HotSpotOriginDao.class).clone();
        hotSpotOriginDaoConfig.initIdentityScope(type);

        endInfoDaoConfig = daoConfigMap.get(EndInfoDao.class).clone();
        endInfoDaoConfig.initIdentityScope(type);

        originEndInfoDaoConfig = daoConfigMap.get(OriginEndInfoDao.class).clone();
        originEndInfoDaoConfig.initIdentityScope(type);

        originInfoDaoConfig = daoConfigMap.get(OriginInfoDao.class).clone();
        originInfoDaoConfig.initIdentityScope(type);

        hotSpotHistorySearchDao = new HotSpotHistorySearchDao(hotSpotHistorySearchDaoConfig, this);
        hotSpotOriginDao = new HotSpotOriginDao(hotSpotOriginDaoConfig, this);
        endInfoDao = new EndInfoDao(endInfoDaoConfig, this);
        originEndInfoDao = new OriginEndInfoDao(originEndInfoDaoConfig, this);
        originInfoDao = new OriginInfoDao(originInfoDaoConfig, this);

        registerDao(HotSpotHistorySearch.class, hotSpotHistorySearchDao);
        registerDao(HotSpotOrigin.class, hotSpotOriginDao);
        registerDao(EndInfo.class, endInfoDao);
        registerDao(OriginEndInfo.class, originEndInfoDao);
        registerDao(OriginInfo.class, originInfoDao);
    }
    
    public void clear() {
        hotSpotHistorySearchDaoConfig.clearIdentityScope();
        hotSpotOriginDaoConfig.clearIdentityScope();
        endInfoDaoConfig.clearIdentityScope();
        originEndInfoDaoConfig.clearIdentityScope();
        originInfoDaoConfig.clearIdentityScope();
    }

    public HotSpotHistorySearchDao getHotSpotHistorySearchDao() {
        return hotSpotHistorySearchDao;
    }

    public HotSpotOriginDao getHotSpotOriginDao() {
        return hotSpotOriginDao;
    }

    public EndInfoDao getEndInfoDao() {
        return endInfoDao;
    }

    public OriginEndInfoDao getOriginEndInfoDao() {
        return originEndInfoDao;
    }

    public OriginInfoDao getOriginInfoDao() {
        return originInfoDao;
    }

}
