package com.aserbao.aserbaosandroid.functions.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.taxidata.ui.passengerpath.enity.EndInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "END_INFO".
*/
public class EndInfoDao extends AbstractDao<EndInfo, Long> {

    public static final String TABLENAME = "END_INFO";

    /**
     * Properties of entity EndInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property End = new Property(1, String.class, "end", false, "END");
        public final static Property Lng = new Property(2, double.class, "lng", false, "LNG");
        public final static Property Lat = new Property(3, double.class, "lat", false, "LAT");
    }


    public EndInfoDao(DaoConfig config) {
        super(config);
    }
    
    public EndInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"END_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"END\" TEXT," + // 1: end
                "\"LNG\" REAL NOT NULL ," + // 2: lng
                "\"LAT\" REAL NOT NULL );"); // 3: lat
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"END_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, EndInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String end = entity.getEnd();
        if (end != null) {
            stmt.bindString(2, end);
        }
        stmt.bindDouble(3, entity.getLng());
        stmt.bindDouble(4, entity.getLat());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, EndInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String end = entity.getEnd();
        if (end != null) {
            stmt.bindString(2, end);
        }
        stmt.bindDouble(3, entity.getLng());
        stmt.bindDouble(4, entity.getLat());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public EndInfo readEntity(Cursor cursor, int offset) {
        EndInfo entity = new EndInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // end
            cursor.getDouble(offset + 2), // lng
            cursor.getDouble(offset + 3) // lat
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, EndInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEnd(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLng(cursor.getDouble(offset + 2));
        entity.setLat(cursor.getDouble(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(EndInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(EndInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(EndInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
