package com.aserbao.aserbaosandroid.functions.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.taxidata.bean.HotSpotOrigin;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOT_SPOT_ORIGIN".
*/
public class HotSpotOriginDao extends AbstractDao<HotSpotOrigin, Long> {

    public static final String TABLENAME = "HOT_SPOT_ORIGIN";

    /**
     * Properties of entity HotSpotOrigin.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "Id", true, "_id");
        public final static Property HotSpotOriginHistory = new Property(1, String.class, "hotSpotOriginHistory", false, "HOT_SPOT_ORIGIN_HISTORY");
    }


    public HotSpotOriginDao(DaoConfig config) {
        super(config);
    }
    
    public HotSpotOriginDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOT_SPOT_ORIGIN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: Id
                "\"HOT_SPOT_ORIGIN_HISTORY\" TEXT);"); // 1: hotSpotOriginHistory
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOT_SPOT_ORIGIN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HotSpotOrigin entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        String hotSpotOriginHistory = entity.getHotSpotOriginHistory();
        if (hotSpotOriginHistory != null) {
            stmt.bindString(2, hotSpotOriginHistory);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HotSpotOrigin entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        String hotSpotOriginHistory = entity.getHotSpotOriginHistory();
        if (hotSpotOriginHistory != null) {
            stmt.bindString(2, hotSpotOriginHistory);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HotSpotOrigin readEntity(Cursor cursor, int offset) {
        HotSpotOrigin entity = new HotSpotOrigin( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // hotSpotOriginHistory
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HotSpotOrigin entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHotSpotOriginHistory(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HotSpotOrigin entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HotSpotOrigin entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HotSpotOrigin entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
