package com.aserbao.aserbaosandroid.functions.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.taxidata.bean.HotSpotHistorySearch;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOT_SPOT_HISTORY_SEARCH".
*/
public class HotSpotHistorySearchDao extends AbstractDao<HotSpotHistorySearch, Long> {

    public static final String TABLENAME = "HOT_SPOT_HISTORY_SEARCH";

    /**
     * Properties of entity HotSpotHistorySearch.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, Long.class, "ID", true, "_id");
        public final static Property HotSpotHistory = new Property(1, String.class, "hotSpotHistory", false, "HOT_SPOT_HISTORY");
    }


    public HotSpotHistorySearchDao(DaoConfig config) {
        super(config);
    }
    
    public HotSpotHistorySearchDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOT_SPOT_HISTORY_SEARCH\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: ID
                "\"HOT_SPOT_HISTORY\" TEXT);"); // 1: hotSpotHistory
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOT_SPOT_HISTORY_SEARCH\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HotSpotHistorySearch entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
 
        String hotSpotHistory = entity.getHotSpotHistory();
        if (hotSpotHistory != null) {
            stmt.bindString(2, hotSpotHistory);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HotSpotHistorySearch entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
 
        String hotSpotHistory = entity.getHotSpotHistory();
        if (hotSpotHistory != null) {
            stmt.bindString(2, hotSpotHistory);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HotSpotHistorySearch readEntity(Cursor cursor, int offset) {
        HotSpotHistorySearch entity = new HotSpotHistorySearch( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // hotSpotHistory
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HotSpotHistorySearch entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHotSpotHistory(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HotSpotHistorySearch entity, long rowId) {
        entity.setID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HotSpotHistorySearch entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HotSpotHistorySearch entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
