package com.aserbao.aserbaosandroid.functions.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.taxidata.ui.passengerpath.enity.OriginInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ORIGIN_INFO".
*/
public class OriginInfoDao extends AbstractDao<OriginInfo, Long> {

    public static final String TABLENAME = "ORIGIN_INFO";

    /**
     * Properties of entity OriginInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Origin = new Property(1, String.class, "origin", false, "ORIGIN");
        public final static Property Lng = new Property(2, double.class, "lng", false, "LNG");
        public final static Property Lat = new Property(3, double.class, "lat", false, "LAT");
    }


    public OriginInfoDao(DaoConfig config) {
        super(config);
    }
    
    public OriginInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ORIGIN_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ORIGIN\" TEXT," + // 1: origin
                "\"LNG\" REAL NOT NULL ," + // 2: lng
                "\"LAT\" REAL NOT NULL );"); // 3: lat
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ORIGIN_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OriginInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String origin = entity.getOrigin();
        if (origin != null) {
            stmt.bindString(2, origin);
        }
        stmt.bindDouble(3, entity.getLng());
        stmt.bindDouble(4, entity.getLat());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OriginInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String origin = entity.getOrigin();
        if (origin != null) {
            stmt.bindString(2, origin);
        }
        stmt.bindDouble(3, entity.getLng());
        stmt.bindDouble(4, entity.getLat());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OriginInfo readEntity(Cursor cursor, int offset) {
        OriginInfo entity = new OriginInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // origin
            cursor.getDouble(offset + 2), // lng
            cursor.getDouble(offset + 3) // lat
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OriginInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setOrigin(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLng(cursor.getDouble(offset + 2));
        entity.setLat(cursor.getDouble(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OriginInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OriginInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OriginInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
